nombre = input("¿Cuál es tu nombre? ")
apellido = input("¿Cuál es tu apellido? ")
edad = input("¿Cuántos años tienes? ")
lugar = input("¿Dónde vives? ")
print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {lugar}.")